package org.example._backend.dto.impl;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.example._backend.Enum.Role;
import org.example._backend.dto.SuperDTO;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class UserDTO implements SuperDTO {
    @Null(message = "Code generated by server")
    private String user_id;

    @Email
    private String email;
    @NotNull
    private String password;
    @NotNull
    private Role role;

    public UserDTO(String userId, @Email String email, Role role) {
        this.user_id = userId;
        this.email = email;
        this.role = role;
    }

}
